name: 'Build and Push Docker Image'
description: 'Build and Push Docker Image'
inputs:
  registry-url:
    description: 'A registry url where to push the image'
    default: 'docker.io'
    required: false
    type: string
  registry-username:
    description: 'Useraname for the registry'
    required: true
    type: string
  registry-password:
    description: 'Password for the registry'
    required: true
    type: string
  image-name:
    description: 'Name of the image'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Build Docker image
      run: |
        docker build -t ${{ inputs.registry-url }}/${{ inputs.image-name }} .
      shell: bash

    - name: Push Docker image
      run: |
        docker push  ${{ inputs.registry-url }}/${{ inputs.image-name }}
      shell: bash

